version: 3
services:
    redis:
        image: 'redis:alpine'
        container_name: national_clearance_redis_cache
        ports:
            - '6379:6379'
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
